export const generatedUsQuestionBank = [
  {
    id: "us-state-capital-alabama",
    category: "us-geography",
    difficulty: "medium",
    prompt: "What is the capital of Alabama?",
    choices: ["Phoenix", "Montgomery", "Cheyenne", "Juneau"],
    answer: "Montgomery",
    explanation: "Montgomery is the capital of Alabama.",
  },
  {
    id: "us-state-year-alabama",
    category: "us-geography",
    difficulty: "hard",
    prompt: "Which state joined the Union in 1819?",
    choices: ["Michigan", "Minnesota", "Alabama", "Massachusetts"],
    answer: "Alabama",
    explanation: "Alabama entered the Union in 1819.",
  },
  {
    id: "us-state-capital-alaska",
    category: "us-geography",
    difficulty: "medium",
    prompt: "Juneau is the capital of which U.S. state?",
    choices: ["Wisconsin", "Alaska", "Washington", "West Virginia"],
    answer: "Alaska",
    explanation: "Juneau is the capital city of Alaska.",
  },
  {
    id: "us-state-postal-alaska",
    category: "us-geography",
    difficulty: "medium",
    prompt: "What is the postal abbreviation for Alaska?",
    choices: ["WA", "WV", "AK", "VA"],
    answer: "AK",
    explanation: "AK is the postal abbreviation for Alaska.",
  },
  {
    id: "us-state-capital-arizona",
    category: "us-geography",
    difficulty: "medium",
    prompt: "What is the capital of Arizona?",
    choices: ["Trenton", "Phoenix", "Carson City", "Concord"],
    answer: "Phoenix",
    explanation: "Phoenix is the capital of Arizona.",
  },
  {
    id: "us-state-abbr-arizona",
    category: "us-geography",
    difficulty: "medium",
    prompt: "Which state uses the postal abbreviation AZ?",
    choices: ["Wisconsin", "Arizona", "Washington", "West Virginia"],
    answer: "Arizona",
    explanation: "AZ is the postal abbreviation for Arizona.",
  },
  {
    id: "us-state-capital-arkansas",
    category: "us-geography",
    difficulty: "medium",
    prompt: "Little Rock is the capital of which U.S. state?",
    choices: ["Wisconsin", "Wyoming", "Alabama", "Arkansas"],
    answer: "Arkansas",
    explanation: "Little Rock is the capital city of Arkansas.",
  },
  {
    id: "us-state-year-arkansas",
    category: "us-geography",
    difficulty: "hard",
    prompt: "Which state joined the Union in 1836?",
    choices: ["Arkansas", "Massachusetts", "Michigan", "Minnesota"],
    answer: "Arkansas",
    explanation: "Arkansas entered the Union in 1836.",
  },
  {
    id: "us-state-capital-california",
    category: "us-geography",
    difficulty: "medium",
    prompt: "What is the capital of California?",
    choices: ["Boston", "Lansing", "Saint Paul", "Sacramento"],
    answer: "Sacramento",
    explanation: "Sacramento is the capital of California.",
  },
  {
    id: "us-state-abbr-california",
    category: "us-geography",
    difficulty: "medium",
    prompt: "Which state uses the postal abbreviation CA?",
    choices: ["California", "Delaware", "Florida", "Georgia"],
    answer: "California",
    explanation: "CA is the postal abbreviation for California.",
  },
  {
    id: "us-state-capital-colorado",
    category: "us-geography",
    difficulty: "medium",
    prompt: "Denver is the capital of which U.S. state?",
    choices: ["Pennsylvania", "Rhode Island", "South Carolina", "Colorado"],
    answer: "Colorado",
    explanation: "Denver is the capital city of Colorado.",
  },
  {
    id: "us-state-postal-colorado",
    category: "us-geography",
    difficulty: "medium",
    prompt: "What is the postal abbreviation for Colorado?",
    choices: ["LA", "ME", "CO", "KY"],
    answer: "CO",
    explanation: "CO is the postal abbreviation for Colorado.",
  },
  {
    id: "us-state-capital-connecticut",
    category: "us-geography",
    difficulty: "medium",
    prompt: "What is the capital of Connecticut?",
    choices: ["Hartford", "Boston", "Lansing", "Saint Paul"],
    answer: "Hartford",
    explanation: "Hartford is the capital of Connecticut.",
  },
  {
    id: "us-state-abbr-connecticut",
    category: "us-geography",
    difficulty: "medium",
    prompt: "Which state uses the postal abbreviation CT?",
    choices: ["Connecticut", "New Jersey", "New Mexico", "New York"],
    answer: "Connecticut",
    explanation: "CT is the postal abbreviation for Connecticut.",
  },
  {
    id: "us-state-capital-delaware",
    category: "us-geography",
    difficulty: "medium",
    prompt: "Dover is the capital of which U.S. state?",
    choices: ["Nebraska", "Nevada", "New Hampshire", "Delaware"],
    answer: "Delaware",
    explanation: "Dover is the capital city of Delaware.",
  },
  {
    id: "us-state-postal-delaware",
    category: "us-geography",
    difficulty: "medium",
    prompt: "What is the postal abbreviation for Delaware?",
    choices: ["CO", "CT", "DE", "CA"],
    answer: "DE",
    explanation: "DE is the postal abbreviation for Delaware.",
  },
  {
    id: "us-state-capital-florida",
    category: "us-geography",
    difficulty: "medium",
    prompt: "What is the capital of Florida?",
    choices: ["Tallahassee", "Little Rock", "Sacramento", "Denver"],
    answer: "Tallahassee",
    explanation: "Tallahassee is the capital of Florida.",
  },
  {
    id: "us-state-abbr-florida",
    category: "us-geography",
    difficulty: "medium",
    prompt: "Which state uses the postal abbreviation FL?",
    choices: ["Florida", "Mississippi", "Missouri", "Montana"],
    answer: "Florida",
    explanation: "FL is the postal abbreviation for Florida.",
  },
  {
    id: "us-state-capital-georgia",
    category: "us-geography",
    difficulty: "medium",
    prompt: "Atlanta is the capital of which U.S. state?",
    choices: ["Virginia", "Washington", "West Virginia", "Georgia"],
    answer: "Georgia",
    explanation: "Atlanta is the capital city of Georgia.",
  },
  {
    id: "us-state-postal-georgia",
    category: "us-geography",
    difficulty: "medium",
    prompt: "What is the postal abbreviation for Georgia?",
    choices: ["OH", "OK", "OR", "GA"],
    answer: "GA",
    explanation: "GA is the postal abbreviation for Georgia.",
  },
  {
    id: "us-state-capital-hawaii",
    category: "us-geography",
    difficulty: "medium",
    prompt: "What is the capital of Hawaii?",
    choices: ["Oklahoma City", "Salem", "Harrisburg", "Honolulu"],
    answer: "Honolulu",
    explanation: "Honolulu is the capital of Hawaii.",
  },
  {
    id: "us-state-abbr-hawaii",
    category: "us-geography",
    difficulty: "medium",
    prompt: "Which state uses the postal abbreviation HI?",
    choices: ["Hawaii", "North Carolina", "North Dakota", "Ohio"],
    answer: "Hawaii",
    explanation: "HI is the postal abbreviation for Hawaii.",
  },
  {
    id: "us-state-capital-idaho",
    category: "us-geography",
    difficulty: "medium",
    prompt: "Boise is the capital of which U.S. state?",
    choices: ["Idaho", "Massachusetts", "Michigan", "Minnesota"],
    answer: "Idaho",
    explanation: "Boise is the capital city of Idaho.",
  },
  {
    id: "us-state-postal-idaho",
    category: "us-geography",
    difficulty: "medium",
    prompt: "What is the postal abbreviation for Idaho?",
    choices: ["NM", "NY", "ID", "NJ"],
    answer: "ID",
    explanation: "ID is the postal abbreviation for Idaho.",
  },
  {
    id: "us-state-capital-illinois",
    category: "us-geography",
    difficulty: "medium",
    prompt: "What is the capital of Illinois?",
    choices: ["Annapolis", "Springfield", "Baton Rouge", "Augusta"],
    answer: "Springfield",
    explanation: "Springfield is the capital of Illinois.",
  },
  {
    id: "us-state-year-illinois",
    category: "us-geography",
    difficulty: "hard",
    prompt: "Which state joined the Union in 1818?",
    choices: ["New York", "Illinois", "New Jersey", "New Mexico"],
    answer: "Illinois",
    explanation: "Illinois entered the Union in 1818.",
  },
  {
    id: "us-state-capital-indiana",
    category: "us-geography",
    difficulty: "medium",
    prompt: "Indianapolis is the capital of which U.S. state?",
    choices: ["Indiana", "North Carolina", "North Dakota", "Ohio"],
    answer: "Indiana",
    explanation: "Indianapolis is the capital city of Indiana.",
  },
  {
    id: "us-state-postal-indiana",
    category: "us-geography",
    difficulty: "medium",
    prompt: "What is the postal abbreviation for Indiana?",
    choices: ["IN", "MI", "MN", "MS"],
    answer: "IN",
    explanation: "IN is the postal abbreviation for Indiana.",
  },
  {
    id: "us-state-capital-iowa",
    category: "us-geography",
    difficulty: "medium",
    prompt: "What is the capital of Iowa?",
    choices: ["Topeka", "Des Moines", "Springfield", "Indianapolis"],
    answer: "Des Moines",
    explanation: "Des Moines is the capital of Iowa.",
  },
  {
    id: "us-state-abbr-iowa",
    category: "us-geography",
    difficulty: "medium",
    prompt: "Which state uses the postal abbreviation IA?",
    choices: ["Iowa", "Kansas", "Kentucky", "Louisiana"],
    answer: "Iowa",
    explanation: "IA is the postal abbreviation for Iowa.",
  },
  {
    id: "us-state-capital-kansas",
    category: "us-geography",
    difficulty: "medium",
    prompt: "Topeka is the capital of which U.S. state?",
    choices: ["Kansas", "Georgia", "Hawaii", "Idaho"],
    answer: "Kansas",
    explanation: "Topeka is the capital city of Kansas.",
  },
  {
    id: "us-state-year-kansas",
    category: "us-geography",
    difficulty: "hard",
    prompt: "Which state joined the Union in 1861?",
    choices: ["Indiana", "Kansas", "Idaho", "Illinois"],
    answer: "Kansas",
    explanation: "Kansas entered the Union in 1861.",
  },
  {
    id: "us-state-capital-kentucky",
    category: "us-geography",
    difficulty: "medium",
    prompt: "What is the capital of Kentucky?",
    choices: ["Boise", "Springfield", "Frankfort", "Honolulu"],
    answer: "Frankfort",
    explanation: "Frankfort is the capital of Kentucky.",
  },
  {
    id: "us-state-abbr-kentucky",
    category: "us-geography",
    difficulty: "medium",
    prompt: "Which state uses the postal abbreviation KY?",
    choices: ["California", "Kentucky", "Arizona", "Arkansas"],
    answer: "Kentucky",
    explanation: "KY is the postal abbreviation for Kentucky.",
  },
  {
    id: "us-state-capital-louisiana",
    category: "us-geography",
    difficulty: "medium",
    prompt: "Baton Rouge is the capital of which U.S. state?",
    choices: ["New Mexico", "Louisiana", "New Hampshire", "New Jersey"],
    answer: "Louisiana",
    explanation: "Baton Rouge is the capital city of Louisiana.",
  },
  {
    id: "us-state-postal-louisiana",
    category: "us-geography",
    difficulty: "medium",
    prompt: "What is the postal abbreviation for Louisiana?",
    choices: ["WA", "WV", "WI", "LA"],
    answer: "LA",
    explanation: "LA is the postal abbreviation for Louisiana.",
  },
  {
    id: "us-state-capital-maine",
    category: "us-geography",
    difficulty: "medium",
    prompt: "What is the capital of Maine?",
    choices: ["Augusta", "Concord", "Trenton", "Santa Fe"],
    answer: "Augusta",
    explanation: "Augusta is the capital of Maine.",
  },
  {
    id: "us-state-year-maine",
    category: "us-geography",
    difficulty: "hard",
    prompt: "Which state joined the Union in 1820?",
    choices: ["Iowa", "Kansas", "Kentucky", "Maine"],
    answer: "Maine",
    explanation: "Maine entered the Union in 1820.",
  },
  {
    id: "us-state-capital-maryland",
    category: "us-geography",
    difficulty: "medium",
    prompt: "Annapolis is the capital of which U.S. state?",
    choices: ["Hawaii", "Idaho", "Illinois", "Maryland"],
    answer: "Maryland",
    explanation: "Annapolis is the capital city of Maryland.",
  },
  {
    id: "us-state-postal-maryland",
    category: "us-geography",
    difficulty: "medium",
    prompt: "What is the postal abbreviation for Maryland?",
    choices: ["SD", "TN", "MD", "SC"],
    answer: "MD",
    explanation: "MD is the postal abbreviation for Maryland.",
  },
  {
    id: "us-state-capital-massachusetts",
    category: "us-geography",
    difficulty: "medium",
    prompt: "What is the capital of Massachusetts?",
    choices: ["Boston", "Phoenix", "Little Rock", "Sacramento"],
    answer: "Boston",
    explanation: "Boston is the capital of Massachusetts.",
  },
  {
    id: "us-state-abbr-massachusetts",
    category: "us-geography",
    difficulty: "medium",
    prompt: "Which state uses the postal abbreviation MA?",
    choices: ["Delaware", "Florida", "Massachusetts", "Connecticut"],
    answer: "Massachusetts",
    explanation: "MA is the postal abbreviation for Massachusetts.",
  },
  {
    id: "us-state-capital-michigan",
    category: "us-geography",
    difficulty: "medium",
    prompt: "Lansing is the capital of which U.S. state?",
    choices: ["New York", "North Carolina", "Michigan", "New Mexico"],
    answer: "Michigan",
    explanation: "Lansing is the capital city of Michigan.",
  },
  {
    id: "us-state-year-michigan",
    category: "us-geography",
    difficulty: "hard",
    prompt: "Which state joined the Union in 1837?",
    choices: ["Alaska", "Arizona", "Arkansas", "Michigan"],
    answer: "Michigan",
    explanation: "Michigan entered the Union in 1837.",
  },
  {
    id: "us-state-capital-minnesota",
    category: "us-geography",
    difficulty: "medium",
    prompt: "What is the capital of Minnesota?",
    choices: ["Denver", "Saint Paul", "Little Rock", "Sacramento"],
    answer: "Saint Paul",
    explanation: "Saint Paul is the capital of Minnesota.",
  },
  {
    id: "us-state-abbr-minnesota",
    category: "us-geography",
    difficulty: "medium",
    prompt: "Which state uses the postal abbreviation MN?",
    choices: ["Louisiana", "Maine", "Maryland", "Minnesota"],
    answer: "Minnesota",
    explanation: "MN is the postal abbreviation for Minnesota.",
  },
  {
    id: "us-state-capital-mississippi",
    category: "us-geography",
    difficulty: "medium",
    prompt: "Jackson is the capital of which U.S. state?",
    choices: ["Illinois", "Indiana", "Mississippi", "Idaho"],
    answer: "Mississippi",
    explanation: "Jackson is the capital city of Mississippi.",
  },
  {
    id: "us-state-postal-mississippi",
    category: "us-geography",
    difficulty: "medium",
    prompt: "What is the postal abbreviation for Mississippi?",
    choices: ["HI", "ID", "MS", "GA"],
    answer: "MS",
    explanation: "MS is the postal abbreviation for Mississippi.",
  },
  {
    id: "us-state-capital-missouri",
    category: "us-geography",
    difficulty: "medium",
    prompt: "What is the capital of Missouri?",
    choices: ["Montpelier", "Richmond", "Jefferson City", "Salt Lake City"],
    answer: "Jefferson City",
    explanation: "Jefferson City is the capital of Missouri.",
  },
  {
    id: "us-state-year-missouri",
    category: "us-geography",
    difficulty: "hard",
    prompt: "Which state joined the Union in 1821?",
    choices: ["Connecticut", "Delaware", "Missouri", "Colorado"],
    answer: "Missouri",
    explanation: "Missouri entered the Union in 1821.",
  },
  {
    id: "us-state-capital-montana",
    category: "us-geography",
    difficulty: "medium",
    prompt: "Helena is the capital of which U.S. state?",
    choices: ["Montana", "Rhode Island", "South Carolina", "South Dakota"],
    answer: "Montana",
    explanation: "Helena is the capital city of Montana.",
  },
  {
    id: "us-state-postal-montana",
    category: "us-geography",
    difficulty: "medium",
    prompt: "What is the postal abbreviation for Montana?",
    choices: ["MT", "NV", "NH", "NJ"],
    answer: "MT",
    explanation: "MT is the postal abbreviation for Montana.",
  },
  {
    id: "us-state-capital-nebraska",
    category: "us-geography",
    difficulty: "medium",
    prompt: "What is the capital of Nebraska?",
    choices: ["Raleigh", "Bismarck", "Columbus", "Lincoln"],
    answer: "Lincoln",
    explanation: "Lincoln is the capital of Nebraska.",
  },
  {
    id: "us-state-abbr-nebraska",
    category: "us-geography",
    difficulty: "medium",
    prompt: "Which state uses the postal abbreviation NE?",
    choices: ["Missouri", "Montana", "Nebraska", "Mississippi"],
    answer: "Nebraska",
    explanation: "NE is the postal abbreviation for Nebraska.",
  },
  {
    id: "us-state-capital-nevada",
    category: "us-geography",
    difficulty: "medium",
    prompt: "Carson City is the capital of which U.S. state?",
    choices: ["Ohio", "Oklahoma", "Nevada", "North Dakota"],
    answer: "Nevada",
    explanation: "Carson City is the capital city of Nevada.",
  },
  {
    id: "us-state-year-nevada",
    category: "us-geography",
    difficulty: "hard",
    prompt: "Which state joined the Union in 1864?",
    choices: ["Oklahoma", "Oregon", "Pennsylvania", "Nevada"],
    answer: "Nevada",
    explanation: "Nevada entered the Union in 1864.",
  },
  {
    id: "us-state-capital-new-hampshire",
    category: "us-geography",
    difficulty: "medium",
    prompt: "What is the capital of New Hampshire?",
    choices: ["Charleston", "Madison", "Concord", "Olympia"],
    answer: "Concord",
    explanation: "Concord is the capital of New Hampshire.",
  },
  {
    id: "us-state-abbr-new-hampshire",
    category: "us-geography",
    difficulty: "medium",
    prompt: "Which state uses the postal abbreviation NH?",
    choices: ["New Hampshire", "Alabama", "Alaska", "Arizona"],
    answer: "New Hampshire",
    explanation: "NH is the postal abbreviation for New Hampshire.",
  },
  {
    id: "us-state-capital-new-jersey",
    category: "us-geography",
    difficulty: "medium",
    prompt: "Trenton is the capital of which U.S. state?",
    choices: ["New Jersey", "Virginia", "Washington", "West Virginia"],
    answer: "New Jersey",
    explanation: "Trenton is the capital city of New Jersey.",
  },
  {
    id: "us-state-postal-new-jersey",
    category: "us-geography",
    difficulty: "medium",
    prompt: "What is the postal abbreviation for New Jersey?",
    choices: ["CO", "NJ", "AR", "CA"],
    answer: "NJ",
    explanation: "NJ is the postal abbreviation for New Jersey.",
  },
  {
    id: "us-state-capital-new-mexico",
    category: "us-geography",
    difficulty: "medium",
    prompt: "What is the capital of New Mexico?",
    choices: ["Santa Fe", "Columbus", "Oklahoma City", "Salem"],
    answer: "Santa Fe",
    explanation: "Santa Fe is the capital of New Mexico.",
  },
  {
    id: "us-state-abbr-new-mexico",
    category: "us-geography",
    difficulty: "medium",
    prompt: "Which state uses the postal abbreviation NM?",
    choices: ["Minnesota", "New Mexico", "Massachusetts", "Michigan"],
    answer: "New Mexico",
    explanation: "NM is the postal abbreviation for New Mexico.",
  },
  {
    id: "us-state-capital-new-york",
    category: "us-geography",
    difficulty: "medium",
    prompt: "Albany is the capital of which U.S. state?",
    choices: ["Colorado", "Connecticut", "New York", "California"],
    answer: "New York",
    explanation: "Albany is the capital city of New York.",
  },
  {
    id: "us-state-postal-new-york",
    category: "us-geography",
    difficulty: "medium",
    prompt: "What is the postal abbreviation for New York?",
    choices: ["OK", "NY", "ND", "OH"],
    answer: "NY",
    explanation: "NY is the postal abbreviation for New York.",
  },
  {
    id: "us-state-capital-north-carolina",
    category: "us-geography",
    difficulty: "medium",
    prompt: "What is the capital of North Carolina?",
    choices: ["Providence", "Columbia", "Raleigh", "Harrisburg"],
    answer: "Raleigh",
    explanation: "Raleigh is the capital of North Carolina.",
  },
  {
    id: "us-state-abbr-north-carolina",
    category: "us-geography",
    difficulty: "medium",
    prompt: "Which state uses the postal abbreviation NC?",
    choices: ["Indiana", "Iowa", "Kansas", "North Carolina"],
    answer: "North Carolina",
    explanation: "NC is the postal abbreviation for North Carolina.",
  },
  {
    id: "us-state-capital-north-dakota",
    category: "us-geography",
    difficulty: "medium",
    prompt: "Bismarck is the capital of which U.S. state?",
    choices: ["New Mexico", "North Dakota", "New Hampshire", "New Jersey"],
    answer: "North Dakota",
    explanation: "Bismarck is the capital city of North Dakota.",
  },
  {
    id: "us-state-postal-north-dakota",
    category: "us-geography",
    difficulty: "medium",
    prompt: "What is the postal abbreviation for North Dakota?",
    choices: ["ND", "KY", "LA", "ME"],
    answer: "ND",
    explanation: "ND is the postal abbreviation for North Dakota.",
  },
  {
    id: "us-state-capital-ohio",
    category: "us-geography",
    difficulty: "medium",
    prompt: "What is the capital of Ohio?",
    choices: ["Phoenix", "Little Rock", "Sacramento", "Columbus"],
    answer: "Columbus",
    explanation: "Columbus is the capital of Ohio.",
  },
  {
    id: "us-state-abbr-ohio",
    category: "us-geography",
    difficulty: "medium",
    prompt: "Which state uses the postal abbreviation OH?",
    choices: ["Colorado", "Connecticut", "Ohio", "California"],
    answer: "Ohio",
    explanation: "OH is the postal abbreviation for Ohio.",
  },
  {
    id: "us-state-capital-oklahoma",
    category: "us-geography",
    difficulty: "medium",
    prompt: "Oklahoma City is the capital of which U.S. state?",
    choices: ["Colorado", "Connecticut", "Oklahoma", "California"],
    answer: "Oklahoma",
    explanation: "Oklahoma City is the capital city of Oklahoma.",
  },
  {
    id: "us-state-postal-oklahoma",
    category: "us-geography",
    difficulty: "medium",
    prompt: "What is the postal abbreviation for Oklahoma?",
    choices: ["OH", "OK", "NC", "ND"],
    answer: "OK",
    explanation: "OK is the postal abbreviation for Oklahoma.",
  },
  {
    id: "us-state-capital-oregon",
    category: "us-geography",
    difficulty: "medium",
    prompt: "What is the capital of Oregon?",
    choices: ["Salem", "Raleigh", "Bismarck", "Columbus"],
    answer: "Salem",
    explanation: "Salem is the capital of Oregon.",
  },
  {
    id: "us-state-year-oregon",
    category: "us-geography",
    difficulty: "hard",
    prompt: "Which state joined the Union in 1859?",
    choices: ["Illinois", "Indiana", "Oregon", "Idaho"],
    answer: "Oregon",
    explanation: "Oregon entered the Union in 1859.",
  },
  {
    id: "us-state-capital-pennsylvania",
    category: "us-geography",
    difficulty: "medium",
    prompt: "Harrisburg is the capital of which U.S. state?",
    choices: ["New York", "North Carolina", "North Dakota", "Pennsylvania"],
    answer: "Pennsylvania",
    explanation: "Harrisburg is the capital city of Pennsylvania.",
  },
  {
    id: "us-state-postal-pennsylvania",
    category: "us-geography",
    difficulty: "medium",
    prompt: "What is the postal abbreviation for Pennsylvania?",
    choices: ["MA", "MI", "PA", "MD"],
    answer: "PA",
    explanation: "PA is the postal abbreviation for Pennsylvania.",
  },
  {
    id: "us-state-capital-rhode-island",
    category: "us-geography",
    difficulty: "medium",
    prompt: "What is the capital of Rhode Island?",
    choices: ["Columbus", "Oklahoma City", "Providence", "Bismarck"],
    answer: "Providence",
    explanation: "Providence is the capital of Rhode Island.",
  },
  {
    id: "us-state-abbr-rhode-island",
    category: "us-geography",
    difficulty: "medium",
    prompt: "Which state uses the postal abbreviation RI?",
    choices: ["Louisiana", "Rhode Island", "Kansas", "Kentucky"],
    answer: "Rhode Island",
    explanation: "RI is the postal abbreviation for Rhode Island.",
  },
  {
    id: "us-state-capital-south-carolina",
    category: "us-geography",
    difficulty: "medium",
    prompt: "Columbia is the capital of which U.S. state?",
    choices: ["Louisiana", "South Carolina", "Kansas", "Kentucky"],
    answer: "South Carolina",
    explanation: "Columbia is the capital city of South Carolina.",
  },
  {
    id: "us-state-postal-south-carolina",
    category: "us-geography",
    difficulty: "medium",
    prompt: "What is the postal abbreviation for South Carolina?",
    choices: ["ND", "OH", "SC", "NC"],
    answer: "SC",
    explanation: "SC is the postal abbreviation for South Carolina.",
  },
  {
    id: "us-state-capital-south-dakota",
    category: "us-geography",
    difficulty: "medium",
    prompt: "What is the capital of South Dakota?",
    choices: ["Pierre", "Sacramento", "Denver", "Hartford"],
    answer: "Pierre",
    explanation: "Pierre is the capital of South Dakota.",
  },
  {
    id: "us-state-abbr-south-dakota",
    category: "us-geography",
    difficulty: "medium",
    prompt: "Which state uses the postal abbreviation SD?",
    choices: ["Oklahoma", "Oregon", "Pennsylvania", "South Dakota"],
    answer: "South Dakota",
    explanation: "SD is the postal abbreviation for South Dakota.",
  },
  {
    id: "us-state-capital-tennessee",
    category: "us-geography",
    difficulty: "medium",
    prompt: "Nashville is the capital of which U.S. state?",
    choices: ["New Hampshire", "New Jersey", "Tennessee", "Nevada"],
    answer: "Tennessee",
    explanation: "Nashville is the capital city of Tennessee.",
  },
  {
    id: "us-state-postal-tennessee",
    category: "us-geography",
    difficulty: "medium",
    prompt: "What is the postal abbreviation for Tennessee?",
    choices: ["TN", "WA", "WV", "WI"],
    answer: "TN",
    explanation: "TN is the postal abbreviation for Tennessee.",
  },
  {
    id: "us-state-capital-texas",
    category: "us-geography",
    difficulty: "medium",
    prompt: "What is the capital of Texas?",
    choices: ["Cheyenne", "Montgomery", "Austin", "Madison"],
    answer: "Austin",
    explanation: "Austin is the capital of Texas.",
  },
  {
    id: "us-state-abbr-texas",
    category: "us-geography",
    difficulty: "medium",
    prompt: "Which state uses the postal abbreviation TX?",
    choices: ["Texas", "Minnesota", "Mississippi", "Missouri"],
    answer: "Texas",
    explanation: "TX is the postal abbreviation for Texas.",
  },
  {
    id: "us-state-capital-utah",
    category: "us-geography",
    difficulty: "medium",
    prompt: "Salt Lake City is the capital of which U.S. state?",
    choices: ["Utah", "South Dakota", "Tennessee", "Texas"],
    answer: "Utah",
    explanation: "Salt Lake City is the capital city of Utah.",
  },
  {
    id: "us-state-postal-utah",
    category: "us-geography",
    difficulty: "medium",
    prompt: "What is the postal abbreviation for Utah?",
    choices: ["HI", "ID", "IL", "UT"],
    answer: "UT",
    explanation: "UT is the postal abbreviation for Utah.",
  },
  {
    id: "us-state-capital-vermont",
    category: "us-geography",
    difficulty: "medium",
    prompt: "What is the capital of Vermont?",
    choices: ["Tallahassee", "Atlanta", "Montpelier", "Dover"],
    answer: "Montpelier",
    explanation: "Montpelier is the capital of Vermont.",
  },
  {
    id: "us-state-abbr-vermont",
    category: "us-geography",
    difficulty: "medium",
    prompt: "Which state uses the postal abbreviation VT?",
    choices: ["Nevada", "New Hampshire", "Vermont", "Nebraska"],
    answer: "Vermont",
    explanation: "VT is the postal abbreviation for Vermont.",
  },
  {
    id: "us-state-capital-virginia",
    category: "us-geography",
    difficulty: "medium",
    prompt: "Richmond is the capital of which U.S. state?",
    choices: ["North Dakota", "Ohio", "Virginia", "North Carolina"],
    answer: "Virginia",
    explanation: "Richmond is the capital city of Virginia.",
  },
  {
    id: "us-state-postal-virginia",
    category: "us-geography",
    difficulty: "medium",
    prompt: "What is the postal abbreviation for Virginia?",
    choices: ["IN", "VA", "ID", "IL"],
    answer: "VA",
    explanation: "VA is the postal abbreviation for Virginia.",
  },
  {
    id: "us-state-capital-washington",
    category: "us-geography",
    difficulty: "medium",
    prompt: "What is the capital of Washington?",
    choices: ["Boise", "Springfield", "Olympia", "Honolulu"],
    answer: "Olympia",
    explanation: "Olympia is the capital of Washington.",
  },
  {
    id: "us-state-abbr-washington",
    category: "us-geography",
    difficulty: "medium",
    prompt: "Which state uses the postal abbreviation WA?",
    choices: ["West Virginia", "Wisconsin", "Wyoming", "Washington"],
    answer: "Washington",
    explanation: "WA is the postal abbreviation for Washington.",
  },
  {
    id: "us-state-capital-west-virginia",
    category: "us-geography",
    difficulty: "medium",
    prompt: "Charleston is the capital of which U.S. state?",
    choices: ["Alabama", "Alaska", "West Virginia", "Wyoming"],
    answer: "West Virginia",
    explanation: "Charleston is the capital city of West Virginia.",
  },
  {
    id: "us-state-postal-west-virginia",
    category: "us-geography",
    difficulty: "medium",
    prompt: "What is the postal abbreviation for West Virginia?",
    choices: ["WV", "NE", "NV", "NH"],
    answer: "WV",
    explanation: "WV is the postal abbreviation for West Virginia.",
  },
  {
    id: "us-state-capital-wisconsin",
    category: "us-geography",
    difficulty: "medium",
    prompt: "What is the capital of Wisconsin?",
    choices: ["Dover", "Tallahassee", "Atlanta", "Madison"],
    answer: "Madison",
    explanation: "Madison is the capital of Wisconsin.",
  },
  {
    id: "us-state-year-wisconsin",
    category: "us-geography",
    difficulty: "hard",
    prompt: "Which state joined the Union in 1848?",
    choices: ["Illinois", "Indiana", "Wisconsin", "Idaho"],
    answer: "Wisconsin",
    explanation: "Wisconsin entered the Union in 1848.",
  },
  {
    id: "us-state-capital-wyoming",
    category: "us-geography",
    difficulty: "medium",
    prompt: "Cheyenne is the capital of which U.S. state?",
    choices: ["Oklahoma", "Wyoming", "North Dakota", "Ohio"],
    answer: "Wyoming",
    explanation: "Cheyenne is the capital city of Wyoming.",
  },
  {
    id: "us-state-postal-wyoming",
    category: "us-geography",
    difficulty: "medium",
    prompt: "What is the postal abbreviation for Wyoming?",
    choices: ["MO", "WY", "MN", "MS"],
    answer: "WY",
    explanation: "WY is the postal abbreviation for Wyoming.",
  },
  {
    id: "president-order-1",
    category: "us-presidents",
    difficulty: "medium",
    prompt: "Who was the 1st president of the United States?",
    choices: [
      "Herbert Hoover",
      "George Washington",
      "Warren G. Harding",
      "Calvin Coolidge",
    ],
    answer: "George Washington",
    explanation:
      "George Washington was the 1st president of the United States.",
  },
  {
    id: "president-term-1",
    category: "us-presidents",
    difficulty: "hard",
    prompt: "Which president served from 1789 to 1797?",
    choices: [
      "Bill Clinton",
      "George W. Bush",
      "Barack Obama",
      "George Washington",
    ],
    answer: "George Washington",
    explanation: "George Washington served from 1789 to 1797.",
  },
  {
    id: "president-order-2",
    category: "us-presidents",
    difficulty: "medium",
    prompt: "John Adams was which numbered president of the United States?",
    choices: ["13th", "14th", "15th", "2nd"],
    answer: "2nd",
    explanation: "John Adams was the 2nd president of the United States.",
  },
  {
    id: "president-term-2",
    category: "us-presidents",
    difficulty: "hard",
    prompt: "Which president served from 1797 to 1801?",
    choices: [
      "John Quincy Adams",
      "Andrew Jackson",
      "John Adams",
      "James Monroe",
    ],
    answer: "John Adams",
    explanation: "John Adams served from 1797 to 1801.",
  },
  {
    id: "president-order-3",
    category: "us-presidents",
    difficulty: "medium",
    prompt: "Who was the 3rd president of the United States?",
    choices: [
      "Andrew Jackson",
      "Martin Van Buren",
      "William Henry Harrison",
      "Thomas Jefferson",
    ],
    answer: "Thomas Jefferson",
    explanation: "Thomas Jefferson was the 3rd president of the United States.",
  },
  {
    id: "president-succession-3",
    category: "us-presidents",
    difficulty: "hard",
    prompt: "Who succeeded John Adams as president?",
    choices: [
      "James Monroe",
      "Thomas Jefferson",
      "John Adams",
      "James Madison",
    ],
    answer: "Thomas Jefferson",
    explanation: "Thomas Jefferson followed John Adams in the presidency.",
  },
  {
    id: "president-order-4",
    category: "us-presidents",
    difficulty: "medium",
    prompt: "James Madison was which numbered president of the United States?",
    choices: ["43rd", "44th", "45th", "4th"],
    answer: "4th",
    explanation: "James Madison was the 4th president of the United States.",
  },
  {
    id: "president-term-4",
    category: "us-presidents",
    difficulty: "hard",
    prompt: "Which president served from 1809 to 1817?",
    choices: ["Joe Biden", "James Madison", "Barack Obama", "Donald Trump"],
    answer: "James Madison",
    explanation: "James Madison served from 1809 to 1817.",
  },
  {
    id: "president-order-5",
    category: "us-presidents",
    difficulty: "medium",
    prompt: "Who was the 5th president of the United States?",
    choices: [
      "Martin Van Buren",
      "William Henry Harrison",
      "John Tyler",
      "James Monroe",
    ],
    answer: "James Monroe",
    explanation: "James Monroe was the 5th president of the United States.",
  },
  {
    id: "president-succession-5",
    category: "us-presidents",
    difficulty: "hard",
    prompt: "Who succeeded James Madison as president?",
    choices: [
      "Andrew Jackson",
      "James Monroe",
      "James Madison",
      "John Quincy Adams",
    ],
    answer: "James Monroe",
    explanation: "James Monroe followed James Madison in the presidency.",
  },
  {
    id: "president-order-6",
    category: "us-presidents",
    difficulty: "medium",
    prompt:
      "John Quincy Adams was which numbered president of the United States?",
    choices: ["35th", "36th", "6th", "34th"],
    answer: "6th",
    explanation:
      "John Quincy Adams was the 6th president of the United States.",
  },
  {
    id: "president-term-6",
    category: "us-presidents",
    difficulty: "hard",
    prompt: "Which president served from 1825 to 1829?",
    choices: [
      "John Quincy Adams",
      "Andrew Johnson",
      "Ulysses S. Grant",
      "Rutherford B. Hayes",
    ],
    answer: "John Quincy Adams",
    explanation: "John Quincy Adams served from 1825 to 1829.",
  },
  {
    id: "president-order-7",
    category: "us-presidents",
    difficulty: "medium",
    prompt: "Who was the 7th president of the United States?",
    choices: [
      "Andrew Jackson",
      "George Washington",
      "John Adams",
      "Thomas Jefferson",
    ],
    answer: "Andrew Jackson",
    explanation: "Andrew Jackson was the 7th president of the United States.",
  },
  {
    id: "president-succession-7",
    category: "us-presidents",
    difficulty: "hard",
    prompt: "Who succeeded John Quincy Adams as president?",
    choices: [
      "Andrew Jackson",
      "James Monroe",
      "John Quincy Adams",
      "Martin Van Buren",
    ],
    answer: "Andrew Jackson",
    explanation: "Andrew Jackson followed John Quincy Adams in the presidency.",
  },
  {
    id: "president-order-8",
    category: "us-presidents",
    difficulty: "medium",
    prompt:
      "Martin Van Buren was which numbered president of the United States?",
    choices: ["15th", "16th", "17th", "8th"],
    answer: "8th",
    explanation: "Martin Van Buren was the 8th president of the United States.",
  },
  {
    id: "president-term-8",
    category: "us-presidents",
    difficulty: "hard",
    prompt: "Which president served from 1837 to 1841?",
    choices: [
      "Martin Van Buren",
      "William McKinley",
      "Theodore Roosevelt",
      "William Howard Taft",
    ],
    answer: "Martin Van Buren",
    explanation: "Martin Van Buren served from 1837 to 1841.",
  },
  {
    id: "president-order-9",
    category: "us-presidents",
    difficulty: "medium",
    prompt: "Who was the 9th president of the United States?",
    choices: [
      "Millard Fillmore",
      "Franklin Pierce",
      "James Buchanan",
      "William Henry Harrison",
    ],
    answer: "William Henry Harrison",
    explanation:
      "William Henry Harrison was the 9th president of the United States.",
  },
  {
    id: "president-succession-9",
    category: "us-presidents",
    difficulty: "hard",
    prompt: "Who succeeded Martin Van Buren as president?",
    choices: [
      "Martin Van Buren",
      "John Tyler",
      "James K. Polk",
      "William Henry Harrison",
    ],
    answer: "William Henry Harrison",
    explanation:
      "William Henry Harrison followed Martin Van Buren in the presidency.",
  },
  {
    id: "president-order-10",
    category: "us-presidents",
    difficulty: "medium",
    prompt: "John Tyler was which numbered president of the United States?",
    choices: ["10th", "6th", "7th", "8th"],
    answer: "10th",
    explanation: "John Tyler was the 10th president of the United States.",
  },
  {
    id: "president-term-10",
    category: "us-presidents",
    difficulty: "hard",
    prompt: "Which president served from 1841 to 1845?",
    choices: ["Barack Obama", "Donald Trump", "Joe Biden", "John Tyler"],
    answer: "John Tyler",
    explanation: "John Tyler served from 1841 to 1845.",
  },
  {
    id: "president-order-11",
    category: "us-presidents",
    difficulty: "medium",
    prompt: "Who was the 11th president of the United States?",
    choices: [
      "James Madison",
      "James Monroe",
      "James K. Polk",
      "Thomas Jefferson",
    ],
    answer: "James K. Polk",
    explanation: "James K. Polk was the 11th president of the United States.",
  },
  {
    id: "president-succession-11",
    category: "us-presidents",
    difficulty: "hard",
    prompt: "Who succeeded John Tyler as president?",
    choices: [
      "William Henry Harrison",
      "John Tyler",
      "Zachary Taylor",
      "James K. Polk",
    ],
    answer: "James K. Polk",
    explanation: "James K. Polk followed John Tyler in the presidency.",
  },
  {
    id: "president-order-12",
    category: "us-presidents",
    difficulty: "medium",
    prompt: "Zachary Taylor was which numbered president of the United States?",
    choices: ["39th", "40th", "41st", "12th"],
    answer: "12th",
    explanation: "Zachary Taylor was the 12th president of the United States.",
  },
  {
    id: "president-term-12",
    category: "us-presidents",
    difficulty: "hard",
    prompt: "Which president served from 1849 to 1850?",
    choices: [
      "Franklin Pierce",
      "James Buchanan",
      "Zachary Taylor",
      "Millard Fillmore",
    ],
    answer: "Zachary Taylor",
    explanation: "Zachary Taylor served from 1849 to 1850.",
  },
  {
    id: "president-order-13",
    category: "us-presidents",
    difficulty: "medium",
    prompt: "Who was the 13th president of the United States?",
    choices: [
      "James Buchanan",
      "Abraham Lincoln",
      "Millard Fillmore",
      "Franklin Pierce",
    ],
    answer: "Millard Fillmore",
    explanation:
      "Millard Fillmore was the 13th president of the United States.",
  },
  {
    id: "president-succession-13",
    category: "us-presidents",
    difficulty: "hard",
    prompt: "Who succeeded Zachary Taylor as president?",
    choices: [
      "Millard Fillmore",
      "Franklin Pierce",
      "James Buchanan",
      "James K. Polk",
    ],
    answer: "Millard Fillmore",
    explanation: "Millard Fillmore followed Zachary Taylor in the presidency.",
  },
  {
    id: "president-order-14",
    category: "us-presidents",
    difficulty: "medium",
    prompt:
      "Franklin Pierce was which numbered president of the United States?",
    choices: ["15th", "16th", "14th", "13th"],
    answer: "14th",
    explanation: "Franklin Pierce was the 14th president of the United States.",
  },
  {
    id: "president-term-14",
    category: "us-presidents",
    difficulty: "hard",
    prompt: "Which president served from 1853 to 1857?",
    choices: [
      "John Quincy Adams",
      "Andrew Jackson",
      "Franklin Pierce",
      "James Monroe",
    ],
    answer: "Franklin Pierce",
    explanation: "Franklin Pierce served from 1853 to 1857.",
  },
  {
    id: "president-order-15",
    category: "us-presidents",
    difficulty: "medium",
    prompt: "Who was the 15th president of the United States?",
    choices: [
      "James Buchanan",
      "James A. Garfield",
      "Chester Arthur",
      "Grover Cleveland",
    ],
    answer: "James Buchanan",
    explanation: "James Buchanan was the 15th president of the United States.",
  },
  {
    id: "president-succession-15",
    category: "us-presidents",
    difficulty: "hard",
    prompt: "Who succeeded Franklin Pierce as president?",
    choices: [
      "James Buchanan",
      "Millard Fillmore",
      "Franklin Pierce",
      "Abraham Lincoln",
    ],
    answer: "James Buchanan",
    explanation: "James Buchanan followed Franklin Pierce in the presidency.",
  },
  {
    id: "president-order-16",
    category: "us-presidents",
    difficulty: "medium",
    prompt:
      "Abraham Lincoln was which numbered president of the United States?",
    choices: ["46th", "1st", "16th", "45th"],
    answer: "16th",
    explanation: "Abraham Lincoln was the 16th president of the United States.",
  },
  {
    id: "president-term-16",
    category: "us-presidents",
    difficulty: "hard",
    prompt: "Which president served from 1861 to 1865?",
    choices: [
      "Gerald Ford",
      "Jimmy Carter",
      "Abraham Lincoln",
      "Richard Nixon",
    ],
    answer: "Abraham Lincoln",
    explanation: "Abraham Lincoln served from 1861 to 1865.",
  },
  {
    id: "president-order-17",
    category: "us-presidents",
    difficulty: "medium",
    prompt: "Who was the 17th president of the United States?",
    choices: [
      "Benjamin Harrison",
      "Grover Cleveland",
      "William McKinley",
      "Andrew Johnson",
    ],
    answer: "Andrew Johnson",
    explanation: "Andrew Johnson was the 17th president of the United States.",
  },
  {
    id: "president-succession-17",
    category: "us-presidents",
    difficulty: "hard",
    prompt: "Who succeeded Abraham Lincoln as president?",
    choices: [
      "Abraham Lincoln",
      "Ulysses S. Grant",
      "Rutherford B. Hayes",
      "Andrew Johnson",
    ],
    answer: "Andrew Johnson",
    explanation: "Andrew Johnson followed Abraham Lincoln in the presidency.",
  },
  {
    id: "president-order-18",
    category: "us-presidents",
    difficulty: "medium",
    prompt:
      "Ulysses S. Grant was which numbered president of the United States?",
    choices: ["32nd", "33rd", "34th", "18th"],
    answer: "18th",
    explanation:
      "Ulysses S. Grant was the 18th president of the United States.",
  },
  {
    id: "president-term-18",
    category: "us-presidents",
    difficulty: "hard",
    prompt: "Which president served from 1869 to 1877?",
    choices: [
      "Ulysses S. Grant",
      "Bill Clinton",
      "George W. Bush",
      "Barack Obama",
    ],
    answer: "Ulysses S. Grant",
    explanation: "Ulysses S. Grant served from 1869 to 1877.",
  },
  {
    id: "president-order-19",
    category: "us-presidents",
    difficulty: "medium",
    prompt: "Who was the 19th president of the United States?",
    choices: [
      "Franklin D. Roosevelt",
      "Harry S. Truman",
      "Rutherford B. Hayes",
      "Herbert Hoover",
    ],
    answer: "Rutherford B. Hayes",
    explanation:
      "Rutherford B. Hayes was the 19th president of the United States.",
  },
  {
    id: "president-succession-19",
    category: "us-presidents",
    difficulty: "hard",
    prompt: "Who succeeded Ulysses S. Grant as president?",
    choices: [
      "James A. Garfield",
      "Rutherford B. Hayes",
      "Andrew Johnson",
      "Ulysses S. Grant",
    ],
    answer: "Rutherford B. Hayes",
    explanation:
      "Rutherford B. Hayes followed Ulysses S. Grant in the presidency.",
  },
  {
    id: "president-order-20",
    category: "us-presidents",
    difficulty: "medium",
    prompt:
      "James A. Garfield was which numbered president of the United States?",
    choices: ["20th", "14th", "15th", "16th"],
    answer: "20th",
    explanation:
      "James A. Garfield was the 20th president of the United States.",
  },
  {
    id: "president-term-20",
    category: "us-presidents",
    difficulty: "hard",
    prompt: "Which president served from 1881 to 1881?",
    choices: [
      "Barack Obama",
      "Donald Trump",
      "James A. Garfield",
      "George W. Bush",
    ],
    answer: "James A. Garfield",
    explanation: "James A. Garfield served from 1881 to 1881.",
  },
  {
    id: "president-order-21",
    category: "us-presidents",
    difficulty: "medium",
    prompt: "Who was the 21st president of the United States?",
    choices: [
      "George W. Bush",
      "Barack Obama",
      "Donald Trump",
      "Chester Arthur",
    ],
    answer: "Chester Arthur",
    explanation: "Chester Arthur was the 21st president of the United States.",
  },
  {
    id: "president-succession-21",
    category: "us-presidents",
    difficulty: "hard",
    prompt: "Who succeeded James A. Garfield as president?",
    choices: [
      "James A. Garfield",
      "Grover Cleveland",
      "Benjamin Harrison",
      "Chester Arthur",
    ],
    answer: "Chester Arthur",
    explanation: "Chester Arthur followed James A. Garfield in the presidency.",
  },
  {
    id: "president-order-22",
    category: "us-presidents",
    difficulty: "medium",
    prompt:
      "Grover Cleveland was which numbered president of the United States?",
    choices: ["33rd", "22nd", "31st", "32nd"],
    answer: "22nd",
    explanation:
      "Grover Cleveland was the 22nd president of the United States.",
  },
  {
    id: "president-term-22",
    category: "us-presidents",
    difficulty: "hard",
    prompt: "Which president served from 1885 to 1889?",
    choices: [
      "James Madison",
      "James Monroe",
      "Grover Cleveland",
      "Thomas Jefferson",
    ],
    answer: "Grover Cleveland",
    explanation: "Grover Cleveland served from 1885 to 1889.",
  },
  {
    id: "president-order-23",
    category: "us-presidents",
    difficulty: "medium",
    prompt: "Who was the 23rd president of the United States?",
    choices: [
      "James Monroe",
      "John Quincy Adams",
      "Andrew Jackson",
      "Benjamin Harrison",
    ],
    answer: "Benjamin Harrison",
    explanation:
      "Benjamin Harrison was the 23rd president of the United States.",
  },
  {
    id: "president-succession-23",
    category: "us-presidents",
    difficulty: "hard",
    prompt: "Who succeeded Grover Cleveland as president?",
    choices: [
      "Benjamin Harrison",
      "William McKinley",
      "Chester Arthur",
      "Grover Cleveland",
    ],
    answer: "Benjamin Harrison",
    explanation:
      "Benjamin Harrison followed Grover Cleveland in the presidency.",
  },
  {
    id: "president-order-24",
    category: "us-presidents",
    difficulty: "medium",
    prompt:
      "Grover Cleveland was which numbered president of the United States?",
    choices: ["33rd", "24th", "31st", "32nd"],
    answer: "24th",
    explanation:
      "Grover Cleveland was the 24th president of the United States.",
  },
  {
    id: "president-term-24",
    category: "us-presidents",
    difficulty: "hard",
    prompt: "Which president served from 1893 to 1897?",
    choices: [
      "James Madison",
      "James Monroe",
      "Grover Cleveland",
      "Thomas Jefferson",
    ],
    answer: "Grover Cleveland",
    explanation: "Grover Cleveland served from 1893 to 1897.",
  },
  {
    id: "president-order-25",
    category: "us-presidents",
    difficulty: "medium",
    prompt: "Who was the 25th president of the United States?",
    choices: [
      "John F. Kennedy",
      "Lyndon B. Johnson",
      "Richard Nixon",
      "William McKinley",
    ],
    answer: "William McKinley",
    explanation:
      "William McKinley was the 25th president of the United States.",
  },
  {
    id: "president-succession-25",
    category: "us-presidents",
    difficulty: "hard",
    prompt: "Who succeeded Grover Cleveland as president?",
    choices: [
      "William Howard Taft",
      "William McKinley",
      "Grover Cleveland",
      "Theodore Roosevelt",
    ],
    answer: "William McKinley",
    explanation:
      "William McKinley followed Grover Cleveland in the presidency.",
  },
  {
    id: "president-order-26",
    category: "us-presidents",
    difficulty: "medium",
    prompt:
      "Theodore Roosevelt was which numbered president of the United States?",
    choices: ["10th", "26th", "8th", "9th"],
    answer: "26th",
    explanation:
      "Theodore Roosevelt was the 26th president of the United States.",
  },
  {
    id: "president-term-26",
    category: "us-presidents",
    difficulty: "hard",
    prompt: "Which president served from 1901 to 1909?",
    choices: [
      "Theodore Roosevelt",
      "William Henry Harrison",
      "John Tyler",
      "James K. Polk",
    ],
    answer: "Theodore Roosevelt",
    explanation: "Theodore Roosevelt served from 1901 to 1909.",
  },
  {
    id: "president-order-27",
    category: "us-presidents",
    difficulty: "medium",
    prompt: "Who was the 27th president of the United States?",
    choices: [
      "William Howard Taft",
      "Barack Obama",
      "Donald Trump",
      "Joe Biden",
    ],
    answer: "William Howard Taft",
    explanation:
      "William Howard Taft was the 27th president of the United States.",
  },
  {
    id: "president-succession-27",
    category: "us-presidents",
    difficulty: "hard",
    prompt: "Who succeeded Theodore Roosevelt as president?",
    choices: [
      "Woodrow Wilson",
      "Warren G. Harding",
      "William McKinley",
      "William Howard Taft",
    ],
    answer: "William Howard Taft",
    explanation:
      "William Howard Taft followed Theodore Roosevelt in the presidency.",
  },
  {
    id: "president-order-28",
    category: "us-presidents",
    difficulty: "medium",
    prompt: "Woodrow Wilson was which numbered president of the United States?",
    choices: ["12th", "28th", "10th", "11th"],
    answer: "28th",
    explanation: "Woodrow Wilson was the 28th president of the United States.",
  },
  {
    id: "president-term-28",
    category: "us-presidents",
    difficulty: "hard",
    prompt: "Which president served from 1913 to 1921?",
    choices: [
      "Woodrow Wilson",
      "Calvin Coolidge",
      "Herbert Hoover",
      "Franklin D. Roosevelt",
    ],
    answer: "Woodrow Wilson",
    explanation: "Woodrow Wilson served from 1913 to 1921.",
  },
  {
    id: "president-order-29",
    category: "us-presidents",
    difficulty: "medium",
    prompt: "Who was the 29th president of the United States?",
    choices: ["Barack Obama", "Donald Trump", "Joe Biden", "Warren G. Harding"],
    answer: "Warren G. Harding",
    explanation:
      "Warren G. Harding was the 29th president of the United States.",
  },
  {
    id: "president-succession-29",
    category: "us-presidents",
    difficulty: "hard",
    prompt: "Who succeeded Woodrow Wilson as president?",
    choices: [
      "Warren G. Harding",
      "Herbert Hoover",
      "William Howard Taft",
      "Woodrow Wilson",
    ],
    answer: "Warren G. Harding",
    explanation: "Warren G. Harding followed Woodrow Wilson in the presidency.",
  },
  {
    id: "president-order-30",
    category: "us-presidents",
    difficulty: "medium",
    prompt:
      "Calvin Coolidge was which numbered president of the United States?",
    choices: ["4th", "5th", "6th", "30th"],
    answer: "30th",
    explanation: "Calvin Coolidge was the 30th president of the United States.",
  },
  {
    id: "president-term-30",
    category: "us-presidents",
    difficulty: "hard",
    prompt: "Which president served from 1923 to 1929?",
    choices: [
      "Bill Clinton",
      "George W. Bush",
      "Barack Obama",
      "Calvin Coolidge",
    ],
    answer: "Calvin Coolidge",
    explanation: "Calvin Coolidge served from 1923 to 1929.",
  },
  {
    id: "president-order-31",
    category: "us-presidents",
    difficulty: "medium",
    prompt: "Who was the 31st president of the United States?",
    choices: [
      "Benjamin Harrison",
      "Grover Cleveland",
      "Herbert Hoover",
      "Grover Cleveland",
    ],
    answer: "Herbert Hoover",
    explanation: "Herbert Hoover was the 31st president of the United States.",
  },
  {
    id: "president-succession-31",
    category: "us-presidents",
    difficulty: "hard",
    prompt: "Who succeeded Calvin Coolidge as president?",
    choices: [
      "Harry S. Truman",
      "Warren G. Harding",
      "Herbert Hoover",
      "Franklin D. Roosevelt",
    ],
    answer: "Herbert Hoover",
    explanation: "Herbert Hoover followed Calvin Coolidge in the presidency.",
  },
  {
    id: "president-order-32",
    category: "us-presidents",
    difficulty: "medium",
    prompt:
      "Franklin D. Roosevelt was which numbered president of the United States?",
    choices: ["41st", "42nd", "43rd", "32nd"],
    answer: "32nd",
    explanation:
      "Franklin D. Roosevelt was the 32nd president of the United States.",
  },
  {
    id: "president-term-32",
    category: "us-presidents",
    difficulty: "hard",
    prompt: "Which president served from 1933 to 1945?",
    choices: [
      "Andrew Jackson",
      "Franklin D. Roosevelt",
      "James Monroe",
      "John Quincy Adams",
    ],
    answer: "Franklin D. Roosevelt",
    explanation: "Franklin D. Roosevelt served from 1933 to 1945.",
  },
  {
    id: "president-order-33",
    category: "us-presidents",
    difficulty: "medium",
    prompt: "Who was the 33rd president of the United States?",
    choices: [
      "Harry S. Truman",
      "Thomas Jefferson",
      "James Madison",
      "James Monroe",
    ],
    answer: "Harry S. Truman",
    explanation: "Harry S. Truman was the 33rd president of the United States.",
  },
  {
    id: "president-succession-33",
    category: "us-presidents",
    difficulty: "hard",
    prompt: "Who succeeded Franklin D. Roosevelt as president?",
    choices: [
      "Dwight D. Eisenhower",
      "John F. Kennedy",
      "Herbert Hoover",
      "Harry S. Truman",
    ],
    answer: "Harry S. Truman",
    explanation:
      "Harry S. Truman followed Franklin D. Roosevelt in the presidency.",
  },
  {
    id: "president-order-34",
    category: "us-presidents",
    difficulty: "medium",
    prompt:
      "Dwight D. Eisenhower was which numbered president of the United States?",
    choices: ["30th", "34th", "28th", "29th"],
    answer: "34th",
    explanation:
      "Dwight D. Eisenhower was the 34th president of the United States.",
  },
  {
    id: "president-term-34",
    category: "us-presidents",
    difficulty: "hard",
    prompt: "Which president served from 1953 to 1961?",
    choices: [
      "Chester Arthur",
      "Grover Cleveland",
      "Dwight D. Eisenhower",
      "James A. Garfield",
    ],
    answer: "Dwight D. Eisenhower",
    explanation: "Dwight D. Eisenhower served from 1953 to 1961.",
  },
  {
    id: "president-order-35",
    category: "us-presidents",
    difficulty: "medium",
    prompt: "Who was the 35th president of the United States?",
    choices: [
      "John F. Kennedy",
      "Chester Arthur",
      "Grover Cleveland",
      "Benjamin Harrison",
    ],
    answer: "John F. Kennedy",
    explanation: "John F. Kennedy was the 35th president of the United States.",
  },
  {
    id: "president-succession-35",
    category: "us-presidents",
    difficulty: "hard",
    prompt: "Who succeeded Dwight D. Eisenhower as president?",
    choices: [
      "Lyndon B. Johnson",
      "Richard Nixon",
      "Harry S. Truman",
      "John F. Kennedy",
    ],
    answer: "John F. Kennedy",
    explanation:
      "John F. Kennedy followed Dwight D. Eisenhower in the presidency.",
  },
  {
    id: "president-order-36",
    category: "us-presidents",
    difficulty: "medium",
    prompt:
      "Lyndon B. Johnson was which numbered president of the United States?",
    choices: ["1st", "2nd", "3rd", "36th"],
    answer: "36th",
    explanation:
      "Lyndon B. Johnson was the 36th president of the United States.",
  },
  {
    id: "president-term-36",
    category: "us-presidents",
    difficulty: "hard",
    prompt: "Which president served from 1963 to 1969?",
    choices: [
      "Herbert Hoover",
      "Lyndon B. Johnson",
      "Warren G. Harding",
      "Calvin Coolidge",
    ],
    answer: "Lyndon B. Johnson",
    explanation: "Lyndon B. Johnson served from 1963 to 1969.",
  },
  {
    id: "president-order-37",
    category: "us-presidents",
    difficulty: "medium",
    prompt: "Who was the 37th president of the United States?",
    choices: [
      "Warren G. Harding",
      "Richard Nixon",
      "William Howard Taft",
      "Woodrow Wilson",
    ],
    answer: "Richard Nixon",
    explanation: "Richard Nixon was the 37th president of the United States.",
  },
  {
    id: "president-succession-37",
    category: "us-presidents",
    difficulty: "hard",
    prompt: "Who succeeded Lyndon B. Johnson as president?",
    choices: [
      "Gerald Ford",
      "Jimmy Carter",
      "Richard Nixon",
      "Lyndon B. Johnson",
    ],
    answer: "Richard Nixon",
    explanation: "Richard Nixon followed Lyndon B. Johnson in the presidency.",
  },
  {
    id: "president-order-38",
    category: "us-presidents",
    difficulty: "medium",
    prompt: "Gerald Ford was which numbered president of the United States?",
    choices: ["44th", "38th", "42nd", "43rd"],
    answer: "38th",
    explanation: "Gerald Ford was the 38th president of the United States.",
  },
  {
    id: "president-term-38",
    category: "us-presidents",
    difficulty: "hard",
    prompt: "Which president served from 1974 to 1977?",
    choices: [
      "Martin Van Buren",
      "Gerald Ford",
      "John Quincy Adams",
      "Andrew Jackson",
    ],
    answer: "Gerald Ford",
    explanation: "Gerald Ford served from 1974 to 1977.",
  },
  {
    id: "president-order-39",
    category: "us-presidents",
    difficulty: "medium",
    prompt: "Who was the 39th president of the United States?",
    choices: [
      "Warren G. Harding",
      "Jimmy Carter",
      "William Howard Taft",
      "Woodrow Wilson",
    ],
    answer: "Jimmy Carter",
    explanation: "Jimmy Carter was the 39th president of the United States.",
  },
  {
    id: "president-succession-39",
    category: "us-presidents",
    difficulty: "hard",
    prompt: "Who succeeded Gerald Ford as president?",
    choices: ["George Bush", "Richard Nixon", "Gerald Ford", "Jimmy Carter"],
    answer: "Jimmy Carter",
    explanation: "Jimmy Carter followed Gerald Ford in the presidency.",
  },
  {
    id: "president-order-40",
    category: "us-presidents",
    difficulty: "medium",
    prompt: "Ronald Reagan was which numbered president of the United States?",
    choices: ["11th", "40th", "9th", "10th"],
    answer: "40th",
    explanation: "Ronald Reagan was the 40th president of the United States.",
  },
  {
    id: "president-term-40",
    category: "us-presidents",
    difficulty: "hard",
    prompt: "Which president served from 1981 to 1989?",
    choices: ["John Tyler", "James K. Polk", "Zachary Taylor", "Ronald Reagan"],
    answer: "Ronald Reagan",
    explanation: "Ronald Reagan served from 1981 to 1989.",
  },
  {
    id: "president-order-41",
    category: "us-presidents",
    difficulty: "medium",
    prompt: "Who was the 41st president of the United States?",
    choices: [
      "Grover Cleveland",
      "William McKinley",
      "Theodore Roosevelt",
      "George Bush",
    ],
    answer: "George Bush",
    explanation: "George Bush was the 41st president of the United States.",
  },
  {
    id: "president-succession-41",
    category: "us-presidents",
    difficulty: "hard",
    prompt: "Who succeeded Ronald Reagan as president?",
    choices: ["Jimmy Carter", "Ronald Reagan", "George Bush", "George W. Bush"],
    answer: "George Bush",
    explanation: "George Bush followed Ronald Reagan in the presidency.",
  },
  {
    id: "president-order-42",
    category: "us-presidents",
    difficulty: "medium",
    prompt: "Bill Clinton was which numbered president of the United States?",
    choices: ["44th", "42nd", "41st", "43rd"],
    answer: "42nd",
    explanation: "Bill Clinton was the 42nd president of the United States.",
  },
  {
    id: "president-term-42",
    category: "us-presidents",
    difficulty: "hard",
    prompt: "Which president served from 1993 to 2001?",
    choices: [
      "William McKinley",
      "Theodore Roosevelt",
      "Bill Clinton",
      "Grover Cleveland",
    ],
    answer: "Bill Clinton",
    explanation: "Bill Clinton served from 1993 to 2001.",
  },
  {
    id: "president-order-43",
    category: "us-presidents",
    difficulty: "medium",
    prompt: "Who was the 43rd president of the United States?",
    choices: [
      "Woodrow Wilson",
      "George W. Bush",
      "Theodore Roosevelt",
      "William Howard Taft",
    ],
    answer: "George W. Bush",
    explanation: "George W. Bush was the 43rd president of the United States.",
  },
  {
    id: "president-succession-43",
    category: "us-presidents",
    difficulty: "hard",
    prompt: "Who succeeded Bill Clinton as president?",
    choices: ["Bill Clinton", "George W. Bush", "Donald Trump", "George Bush"],
    answer: "George W. Bush",
    explanation: "George W. Bush followed Bill Clinton in the presidency.",
  },
  {
    id: "president-order-44",
    category: "us-presidents",
    difficulty: "medium",
    prompt: "Barack Obama was which numbered president of the United States?",
    choices: ["44th", "24th", "25th", "26th"],
    answer: "44th",
    explanation: "Barack Obama was the 44th president of the United States.",
  },
  {
    id: "president-term-44",
    category: "us-presidents",
    difficulty: "hard",
    prompt: "Which president served from 2009 to 2017?",
    choices: [
      "William Henry Harrison",
      "Barack Obama",
      "Andrew Jackson",
      "Martin Van Buren",
    ],
    answer: "Barack Obama",
    explanation: "Barack Obama served from 2009 to 2017.",
  },
  {
    id: "president-order-45",
    category: "us-presidents",
    difficulty: "medium",
    prompt: "Who was the 45th president of the United States?",
    choices: [
      "Donald Trump",
      "Franklin Pierce",
      "James Buchanan",
      "Abraham Lincoln",
    ],
    answer: "Donald Trump",
    explanation: "Donald Trump was the 45th president of the United States.",
  },
  {
    id: "president-succession-45",
    category: "us-presidents",
    difficulty: "hard",
    prompt: "Who succeeded Barack Obama as president?",
    choices: ["Barack Obama", "Joe Biden", "Donald Trump", "George W. Bush"],
    answer: "Donald Trump",
    explanation: "Donald Trump followed Barack Obama in the presidency.",
  },
  {
    id: "president-order-46",
    category: "us-presidents",
    difficulty: "medium",
    prompt: "Joe Biden was which numbered president of the United States?",
    choices: ["46th", "28th", "29th", "30th"],
    answer: "46th",
    explanation: "Joe Biden was the 46th president of the United States.",
  },
  {
    id: "president-term-46",
    category: "us-presidents",
    difficulty: "hard",
    prompt: "Which president served from 2021 to null?",
    choices: ["Thomas Jefferson", "James Madison", "Joe Biden", "John Adams"],
    answer: "Joe Biden",
    explanation: "Joe Biden served from 2021 to null.",
  },
] as const
